---
# tasks file for create
- hosts: all
  become: true
# tasks
# 1. install docker and kubernetes
# 2. install ssh and python
  tasks:
    - name: Install Packages
      ansible.builtin.apt:
        pkg:
          - sshd
          - docker
          - kubernetes
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: yes
        notify:
          - restart docker
          - restart kubernetes

    - name: Disable Password Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
     notify:
       - restart ssh
       
   - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
     notify:
       - restart ssh 
      

