apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: mysql-pv-volume
  reclaimPolicy: Retain
  labels:
    type: local
provisioner: csi.trident.netapp.io
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi