---
# tasks file for ansible-nginx
- name: Install nginx
  apt:
    pkg: nginx
    update_cache: yes
    cache_valid_time: 86400
    state: present
  when: wp_webserver == "nginx"

- include: nginx.yml
  when: wp_webserver == "nginx"