---
# tasks file for packages
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist

- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - python3
    - vim 
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent
    - python3-apt