---
# deploy.yml for kubernetes deployment configuration
- name: Debian | Configure K8S Master Block
  block:
  - name: Debian | Initialise the Kubernetes cluster using kubeadm
    become: true
    command: sudo kubeadm init --pod-network-cidr={{ k8s_pod_network }} --ignore-preflight-errors=all
    args:
      creates: "{{ k8s_admin_config }}"

  - name: Debian | Setup kubeconfig for {{ k8s_user }} user
    file:
      path: "{{ k8s_user_home }}/.kube"
      state: directory
      owner: "{{ k8s_user }}"
      group: "{{ k8s_user }}"
      mode: "0750"
  
  - name: Debian | Copy {{ k8s_admin_config }}
    become: true
    copy:
      src: "{{ k8s_admin_config }}"
      dest: "{{ k8s_user_home }}/.kube/config"
      owner: "{{ k8s_user }}"
      group: "{{ k8s_user }}"
      mode: "0640"
      remote_src: yes
      
  - name: set export 
    ansible.builtin.shell: export KUBECONFIG=/etc/kubernetes/admin.conf

  - name: Debian | Download {{ calico_rbac_url }}
    get_url:
      url: "{{ calico_rbac_url }}"
      dest: "{{ k8s_user_home }}/{{ calico_rbac_config }}"
      owner: "{{ k8s_user }}"
      group: "{{ k8s_user }}"
      mode: "0640"
  
  - name: Debian | Download {{ calico_net_url }}
    get_url:
      url: "{{ calico_net_url }}"
      dest: "{{ k8s_user_home }}/{{ calico_net_config }}"
      owner: "{{ k8s_user }}"
      group: "{{ k8s_user }}"
      mode: "0640"     

  - name: Debian | Set CALICO_IPV4POOL_CIDR to {{ k8s_pod_network }}
    replace:
      path: "{{ k8s_user_home }}/{{ calico_net_config }}"
      regexp: "192.168.0.0/16"
      replace: "{{ k8s_pod_network }}"
  
  - name: Debian | Download {{ dashboard_url }}
    get_url:
      url: "{{ dashboard_url }}"
      dest: "{{ k8s_user_home }}/{{ dashboard_config }}"
      owner: "{{ k8s_user }}"
      group: "{{ k8s_user }}"
      mode: "0640"     

  # - name: Debian | Create calico tigera operator 
  #   become: false
  #   command: kubectl create -f "{{ calico_tigera_operator_url }}"
  #   ignore_errors: true
  
  # - name: Debian | Create calico custom_resources
  #   become: false
  #   command: kubectl create -f "{{ calico_custom_resources_url }}"
  #   ignore_errors: true

  - name: Debian | Install calico pod network {{ calico_rbac_config }}
    become: false
    command: kubectl apply -f "{{ k8s_user_home }}/{{ calico_rbac_config }}"
    ignore_errors: true
  
  - name: Debian | Install calico pod network {{ calico_net_config }}
    become: false
    command: kubectl apply -f "{{ k8s_user_home }}/{{ calico_net_config }}"
    ignore_errors: true

  - name: Debian | Install K8S dashboard {{ dashboard_config }}
    become: false
    command: kubectl apply -f "{{ k8s_user_home }}/{{ dashboard_config }}" --validate=false
    ignore_errors: true
  
  - name: Debian | Create service account
    become: false
    command: kubectl create serviceaccount dashboard -n default
    ignore_errors: true
  
  - name: Debian | Create cluster role binding dashboard-admin
    become: false
    command: kubectl create clusterrolebinding dashboard-admin -n default --clusterrole=cluster-admin --serviceaccount=default:dashboard
    ignore_errors: true
  
  - name: Debian | Create {{ k8s_dashboard_adminuser_config }} for service account
    copy:
      src: "files/{{ k8s_dashboard_adminuser_config }}"
      dest: "{{ k8s_user_home }}/{{ k8s_dashboard_adminuser_config }}"
      owner: "{{ k8s_user }}"
      group: "{{ k8s_user }}"
      mode: "0640"
  #TODO edit dashboard from clusterIP to nodePort
  - name: Debian | Create service account
    become: false
    command: kubectl apply -f "{{ k8s_user_home }}/{{ k8s_dashboard_adminuser_config }}"
    ignore_errors: true
  
  - name: Debian | Create cluster role binding cluster-system-anonymous
    become: false
    command: kubectl create clusterrolebinding cluster-system-anonymous --clusterrole=cluster-admin --user=system:anonymous
    ignore_errors: true
  
  - name: Debian | Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Debian | Copy join command to local file
    become: false
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="{{ k8s_token_file }}"
  # kube proxy
  # kubectl proxy --address='0.0.0.0' --accept-hosts='^*$'
  #command to get token to access dashboard 
  # kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep kubernetes-dashboard | awk '{print $1}')
  # http://3.88.59.51:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login
  when: "'control' in group_names"
  

- name: Debian | Configure K8S Node Block
  block:
  - name: Debian | Setup kubeconfig for {{ k8s_user }} user
    file:
      path: "{{ k8s_user_home }}/.kube"
      state: directory
      owner: "{{ k8s_user }}"
      group: "{{ k8s_user }}"
      mode: "0750"

  - name: Debian | Copy {{ k8s_token_file }} to server location
    copy: 
      src: "{{ k8s_token_file }}"
      dest: "{{ k8s_user_home }}/{{ k8s_token_file }}"
      owner: "{{ k8s_user }}"
      group: "{{ k8s_user }}"
      mode: "0750"

  - name: Debian | Append --ignore-preflight-errors 
    shell: cat "{{ k8s_user_home }}/{{ k8s_token_file }}" | awk '{print $0, "--ignore-preflight-errors=all"}' | tee "{{ k8s_user_home }}/{{ k8s_token_file }}"

  - name: Debian | Join the node to cluster unless file {{ k8s_kubelet_config }} exists
    shell: sudo bash "{{ k8s_user_home }}/{{ k8s_token_file }}"
    ignore_errors: true
    args:
      creates: "{{ k8s_kubelet_config }}"
  when: "'worker' in group_names"
...