---
# tasks file for kube

- name: create Docker config directory
  file: path=/etc/docker state=directory

- name: changing Docker to systemd driver
  copy:
  dest: "/etc/docker/daemon.json"
  content: |
    {
    "exec-opts": ["native.cgroupdriver=systemd"]
    }

- name: install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes' APT repository
  apt_repository:
  repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
  state: present
  filename: 'kubernetes'

- name: install kubelet
  apt:
    name: kubelet=1.22.4-00
    state: present
    update_cache: true

- name: install kubeadm
  apt:
    name: kubeadm=1.22.4-00
    state: present
  
  # if this method (when) does not work use the (delegate_to) method
- name: install kubectl on control plane
  when: inventory_hostname in groups['control_plane']
  apt:
    name: kubectl=1.22.4-00
    state: present
    force: yes
    
# if this method (delegate_to) does not work use the (when) method
- name: install kubectl on control plane
  delegate_to: control_plane
  apt:
    name: kubectl=1.22.4-00
    state: present
    force: yes